language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

script:
  - docker-compose -p "dev" up -d xqa-message-broker
  - mvn -Dgpg.skip clean test

after_success:
  - mvn jacoco:report coveralls:report
